---

- name: "nim_alt_disk_migration demo"
  hosts: "{{ target_system }}"
  gather_facts: false
  remote_user: root
  vars:
    nim_client_v: p9zpa-ansible-test2
    target_disk_v: hdisk1
    target_disk_policy_v: minimize
    lpp_source_v: lpp_72V_2114
    spot_v: spot_72V_2114
    force_target_disk: true
    validate_nim_resources_v: true
    perform_migration_v: true
    test_case_number: 1
  collections:
    - ibm.power_aix
  tasks:

    # Perform a validation of resources only
    - block:
        - import_role:
            name: ibm.power_aix.nim_alt_disk_migration
          vars:

            nim_client: "{{ nim_client_v }}"
            target_disk:
              # disk_name: "{{ target_disk_v }}"
              disk_size_policy: "{{ target_disk_policy_v }}"
              force: "{{ force_target_disk }}"
            lpp_source: "{{ lpp_source_v }}"
            reboot_client: false
            spot: "{{ spot_v }}"
            control_phases:
               validate_nim_resources: "{{ validate_nim_resources_v }}"
               perform_migration: false
      rescue:
        - debug:
            msg: "Something went wrong, but continue"

      when: test_case_number == 1

    - name: Debug exit
      debug:
        msg: "Exiting Playbook. End of tests"
    - meta: end_host

    # Skip the validation and try to perform a migration - but add skip nimadm for testing

    - import_role:
        name: ibm.power_aix.nim_alt_disk_migration
      vars:

        nim_client: "{{ nim_client_v }}"
        target_disk:
          # disk_name: "{{ target_disk_v }}"
          disk_size_policy: "{{ target_disk_policy_v }}"
          force: "{{ force_target_disk }}"
        lpp_source: "{{ lpp_source_v }}"
        reboot_client: false
        spot: "{{ spot_v }}"
        control_phases:
           validate_nim_resources: "{{ validate_nim_resources_v }}"
           perform_migration: "{{ perform_migration_v }}"
        debug_skip_nimadm: true
      when: test_case_number == "2"
      
    # ERROR TEST - Perform a validation of resources - Do not input lpp_source

    # Perform a validation of resources only
    - import_role:
        name: ibm.power_aix.nim_alt_disk_migration
      vars:

        nim_client: "{{ nim_client_v }}"
        target_disk:
          # disk_name: "{{ target_disk_v }}"
          disk_size_policy: "{{ target_disk_policy_v }}"
          force: "{{ force_target_disk }}"
        # lpp_source: "{{ lpp_source_v }}"
        reboot_client: false
        spot: "{{ spot_v }}"
        control_phases:
           validate_nim_resources: "{{ validate_nim_resources_v }}"
           perform_migration: false
      when: test_case_number == "3"

    # Perform a validation of resources only and do not input the spot
    - import_role:
        name: ibm.power_aix.nim_alt_disk_migration
      vars:

        nim_client: "{{ nim_client_v }}"
        target_disk:
          # disk_name: "{{ target_disk_v }}"
          disk_size_policy: "{{ target_disk_policy_v }}"
          force: "{{ force_target_disk }}"
        lpp_source: "{{ lpp_source_v }}"
        reboot_client: false
        # spot: "{{ spot_v }}"
        control_phases:
           validate_nim_resources: "{{ validate_nim_resources_v }}"
           perform_migration: false
      when: test_case_number == "4"



