# This is a basic workflow to help you get started with Actions

name: run ibm.power_aix collection unit tests

# Controls when the action will run. 
on:
  pull_request:
    branches: [ dev-collection ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      working-directory: ./ansible_collections/ibm/power_aix
    strategy:
      matrix:
        python-version: ['3.7']
        
    name: Python ${{ matrix.python-version }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
       
      - name: create ansible collection directory structure
        run: |
          mkdir -p ${{ env.working-directory }}
          mv plugins roles tests Makefile ${{ env.working-directory }}
         
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
    
      - name: install ansible
        run: |
          python -m pip install --upgrade pip
          python -m pip install ansible
          
      - name: install python modules needed for unit testing
        run: |
          make install-unit-test-requirements
        working-directory: ${{ env.working-directory }}
          
      - name: run unit tests
        run: |
          make unit-test
        working-directory: ${{ env.working-directory }}
